### PR TITLE
Align all the elements in navbar

### PR DESCRIPTION
**Pull request by Jai-Marothiya**
# Description

* Fix the navbar items alignment issue.
image

### CODE REVIEW

**Comment by Prashant0664** [comment]
please attach screenshot of the changes made @Jai-Marothiya

**Comment by Jai-Marothiya** [comment]
@Prashant0664 - I attached the changes image.

**Comment by Prashant0664** [comment]
@Jai-Marothiya All things are not aligned for all windows size, things get distorted for M1 mac size window after sign in.

**Comment by Jai-Marothiya** [comment]
@Prashant0664 - Can you share the image for M1 mac size?

**Comment by Prashant0664** [comment]
image

@Jai-Marothiya, I think that you forgot to change for signed-in navbar and just updated navbar without sign-in.

**Comment by Jai-Marothiya** [comment]
@Prashant0664 - I raised new PR with these changes.

**Pull request merged**
